#!/usr/bin/env python3
"""Regenerate the mentee experiences on cohorts.html.

Reads data/mentee-stories-2025.json and rewrites the block between the
stories:start / stories:end markers.

    python3 tools/build_stories.py

The quotations are reproduced exactly as the mentees gave them. If you edit
anything in the JSON, edit the surrounding fields, not the quote.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGE = ROOT / "cohorts.html"
DATA = ROOT / "data" / "mentee-stories-2025.json"
PHOTOS = ROOT / "assets" / "img" / "mentees"
START, END = "<!-- stories:start", "<!-- stories:end -->"


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def initials(name):
    parts = [p for p in re.sub(r"[^A-Za-z ]", " ", name).split() if len(p) > 1]
    return (parts[0][0] + parts[-1][0]).upper() if len(parts) > 1 else name[:2].upper()


def portrait(name):
    for ext in ("jpg", "png", "webp"):
        f = PHOTOS / ("%s.%s" % (slug(name), ext))
        if f.exists():
            # alt is empty on purpose: the name sits right beside it
            return ('<img class="story__img" src="assets/img/mentees/%s" alt="" '
                    'width="160" height="160" loading="lazy" decoding="async">' % f.name)
    return '<span class="story__initials" aria-hidden="true">%s</span>' % initials(name)


def render(s):
    return '''        <article class="story">
          <div class="story__photo">%s</div>
          <div class="story__body">
            <h3 class="story__name">%s</h3>
            <p class="story__affil">%s</p>
            <blockquote class="story__quote">%s</blockquote>
            <dl class="story__meta">
              <div><dt>Project</dt><dd>%s</dd></div>
              <div><dt>Mentor</dt><dd>%s</dd></div>
            </dl>
          </div>
        </article>
''' % (portrait(s["name"]), s["name"], s["affil"], s["quote"], s["project"], s["mentor"])


def main():
    stories = json.loads(DATA.read_text(encoding="utf-8"))["stories"]
    if not stories:
        sys.exit("no stories — refusing to blank the section")
    body = '      <div class="stories">\n%s      </div>\n' % "".join(render(s) for s in stories)

    page = PAGE.read_text(encoding="utf-8")
    i, j = page.index(START), page.index(END) + len(END)
    block = ("      %s — generated by tools/build_stories.py, do not edit by hand -->\n"
             "%s      %s" % (START, body, END))
    new = page[:i].rstrip("\n ") + "\n" + block + page[j:]
    if new == page:
        print("  cohorts.html already current (%d stories)" % len(stories))
        return
    PAGE.write_text(new, encoding="utf-8")
    have = sum(1 for s in stories
               if any((PHOTOS / ("%s.%s" % (slug(s["name"]), e))).exists() for e in ("jpg", "png", "webp")))
    print("  cohorts.html  %d stories, %d with portraits" % (len(stories), have))


if __name__ == "__main__":
    main()
