#!/usr/bin/env python3
"""Regenerate the mentor rosters on mentors.html and mentors-2025.html.

Reads data/mentors-2026.json and data/mentors-2025.json and rewrites the block
between the mentors:start / mentors:end markers on each page. Entries in the
2025 file marked {"ref": true} are resolved from the 2026 file, so a person who
mentors in both cohorts is described in one place only.

A mentor with a headshot in assets/img/mentors/ gets their photo; anyone else
gets their initials. Run after editing either JSON file:

    python3 tools/build_mentors.py
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PHOTOS = ROOT / "assets" / "img" / "mentors"
START, END = "<!-- mentors:start", "<!-- mentors:end -->"


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def initials(name):
    parts = [p for p in re.sub(r"[^A-Za-z ]", " ", name).split() if len(p) > 1]
    return (parts[0][0] + parts[-1][0]).upper() if len(parts) > 1 else name[:2].upper()


def portrait(m, display):
    """A photo where we have one, initials where we do not."""
    for ext in ("jpg", "png", "webp"):
        f = PHOTOS / ("%s.%s" % (slug(m["name"]), ext))
        if f.exists():
            # alt is empty on purpose: the name is adjacent, so alt text would
            # only make a screen reader say it twice
            return ('<img class="profile__img" src="assets/img/mentors/%s" alt="" '
                    'width="160" height="160" loading="lazy" decoding="async">' % f.name)
    return '<span class="profile__initials" aria-hidden="true">%s</span>' % initials(display)


def render(m, display, badge=False):
    kw = "".join('<li>%s</li>' % k for k in m.get("keywords", []))
    links = "".join(
        '<a class="profile__link" href="%s" target="_blank" rel="noopener">%s</a>' % (url, label)
        for label, url in m.get("links", []))
    affil = ('\n            <p class="profile__affil">%s</p>' % m["affil"]) if m.get("affil") else ""
    mark = '\n            <span class="profile__badge">Also mentoring in 2026</span>' if badge else ""
    return '''        <article class="profile">
          <div class="profile__photo">%s</div>
          <div class="profile__body">
            <h3 class="profile__name">%s</h3>%s%s
            <p class="profile__blurb">%s</p>
            <ul class="profile__keywords">%s</ul>
            <p class="profile__links">%s</p>
          </div>
        </article>
''' % (portrait(m, display), display, affil, mark, m.get("blurb", ""), kw, links)


def build(groups, lookup=None):
    out = []
    for g in groups:
        rows = []
        for entry in g["mentors"]:
            display = entry.get("display_name", entry["name"])
            if entry.get("ref"):
                src = lookup[entry["name"]]
                m = dict(src)
                m["name"] = entry["name"]          # photo filename follows the canonical name
                rows.append(render(m, display, badge=True))
            else:
                rows.append(render(entry, display))
        out.append('      <div class="roster__group">\n'
                   '        <p class="eyebrow roster__label">%s</p>\n'
                   '        <div class="profiles">\n%s        </div>\n      </div>\n'
                   % (g["label"], "".join(rows)))
    return "".join(out)


def write(page, body):
    p = ROOT / page
    s = p.read_text(encoding="utf-8")
    i, j = s.index(START), s.index(END) + len(END)
    block = ("      %s — generated by tools/build_mentors.py, do not edit by hand -->\n"
             "%s      %s" % (START, body, END))
    new = s[:i].rstrip("\n ") + "\n" + block + s[j:]
    if new == s:
        print("  %-22s already current" % page)
        return 0
    p.write_text(new, encoding="utf-8")
    n = new.count('class="profile"')
    print("  %-22s %d profiles" % (page, n))
    return n


def main():
    d26 = json.loads((ROOT / "data" / "mentors-2026.json").read_text(encoding="utf-8"))
    d25 = json.loads((ROOT / "data" / "mentors-2025.json").read_text(encoding="utf-8"))
    lookup = {m["name"]: m for g in d26["groups"] for m in g["mentors"]}

    missing = [e["name"] for g in d25["groups"] for e in g["mentors"]
               if e.get("ref") and e["name"] not in lookup]
    if missing:
        sys.exit("unresolved refs in mentors-2025.json: %s" % ", ".join(missing))

    write("mentors.html", build(d26["groups"]))
    write("mentors-2025.html", build(d25["groups"], lookup))

    have = sum(1 for n in {m["name"] for g in d26["groups"] for m in g["mentors"]}
               | {e["name"] for g in d25["groups"] for e in g["mentors"]}
               if any((PHOTOS / ("%s.%s" % (slug(n), x))).exists() for x in ("jpg", "png", "webp")))
    print("  photos present: %d (the rest fall back to initials)" % have)


if __name__ == "__main__":
    main()
