#!/usr/bin/env python3
"""Rewrite the episode list on podcast.html from the YouTube channel feed.

Reads the channel's public RSS — no API key, no token, nothing to expire.
Summaries in data/episodes.json win; any video without one gets a provisional
summary taken from the first sentences of its YouTube description.

Run:  python3 tools/update_podcast.py [--check] [--feed PATH_OR_URL]
      --check  exits 1 if the page is out of date, without writing
      --feed   read the feed from a file or alternate URL (for testing offline)

The script never writes an empty episode list: if the feed cannot be reached or
comes back with no entries, it fails loudly and leaves the page untouched.
"""
import html
import json
import pathlib
import re
import sys
import time
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGE = ROOT / "podcast.html"
DATA = ROOT / "data" / "episodes.json"
FEED = "https://www.youtube.com/feeds/videos.xml?channel_id={}"
NS = {
    "a": "http://www.w3.org/2005/Atom",
    "m": "http://search.yahoo.com/mrss/",
    "yt": "http://www.youtube.com/xml/schemas/2015",
}
START = "<!-- episodes:start"
END = "<!-- episodes:end -->"
MAX_AUTO = 420  # characters of description to keep for an unwritten summary


def auto_summary(description):
    """First few sentences of a YouTube description, tidied."""
    text = " ".join(description.split())
    if not text:
        return "A new conversation in the series. Watch it on YouTube."
    if len(text) <= MAX_AUTO:
        return text
    cut = text[:MAX_AUTO]
    stop = max(cut.rfind(". "), cut.rfind("! "), cut.rfind("? "))
    return (cut[: stop + 1] if stop > 180 else cut.rsplit(" ", 1)[0] + "…")


def fetch(source):
    """Read the feed from a URL or a local path. Retries transient failures."""
    if not source.startswith("http"):
        return ET.fromstring(pathlib.Path(source).read_bytes())
    last = None
    for attempt in range(4):
        try:
            req = urllib.request.Request(
                source, headers={"User-Agent": "Mozilla/5.0 (compatible; bsri-site-updater)"}
            )
            with urllib.request.urlopen(req, timeout=30) as r:
                return ET.fromstring(r.read())
        except (urllib.error.URLError, urllib.error.HTTPError) as exc:
            last = exc
            if attempt < 3:
                time.sleep(5 * (attempt + 1))
    sys.exit("could not read the feed after 4 attempts ({}). Page left unchanged.".format(last))


def render(entries, overrides):
    out = []
    for e in entries:
        vid = e["id"]
        o = overrides.get(vid, {})
        title = o.get("title") or e["title"]
        summary = o.get("summary") or auto_summary(e["description"])
        url = "https://www.youtube.com/watch?v=" + vid
        out.append(
            '        <article class="episode">\n'
            '          <p class="episode__date">{date}</p>\n'
            '          <h2 class="episode__title"><a href="{url}" target="_blank" rel="noopener">{title}</a></h2>\n'
            '          <p class="episode__summary">{summary}</p>\n'
            '          <a class="episode__watch" href="{url}" target="_blank" rel="noopener">Watch on YouTube &rarr;</a>\n'
            "        </article>\n".format(
                date=e["date"],
                url=url,
                title=html.escape(title),
                summary=html.escape(summary),
            )
        )
    return (
        "      {} — generated by tools/update_podcast.py, do not edit by hand -->\n"
        '      <div class="episodes">\n{}      </div>\n      {}'.format(
            START, "".join(out), END
        )
    )


def main():
    check = "--check" in sys.argv
    cfg = json.loads(DATA.read_text(encoding="utf-8"))
    source = FEED.format(cfg["channel_id"])
    if "--feed" in sys.argv:
        source = sys.argv[sys.argv.index("--feed") + 1]
    root = fetch(source)

    entries = []
    for e in root.findall("a:entry", NS):
        published = e.findtext("a:published", namespaces=NS)
        g = e.find("m:group", NS)
        entries.append(
            {
                "id": e.findtext("yt:videoId", namespaces=NS),
                "title": e.findtext("a:title", namespaces=NS) or "",
                "description": (g.findtext("m:description", namespaces=NS) or "") if g is not None else "",
                "published": published,
                "date": datetime.strptime(published[:10], "%Y-%m-%d").strftime("%-d %B %Y"),
            }
        )
    if not entries:
        sys.exit("no entries in feed — refusing to blank the page")
    entries.sort(key=lambda x: x["published"], reverse=True)

    page = PAGE.read_text(encoding="utf-8")
    i, j = page.index(START), page.index(END) + len(END)
    block = render(entries, cfg.get("episodes", {}))
    updated = page[:i].rstrip("\n ") + "\n" + block + page[j:]

    missing = [e["id"] for e in entries if e["id"] not in cfg.get("episodes", {})]
    if missing:
        print("note: auto-summary used for {} — add a written one to data/episodes.json".format(", ".join(missing)))

    if updated == page:
        print("podcast.html already current ({} episodes)".format(len(entries)))
        return
    if check:
        sys.exit("podcast.html is out of date — run tools/update_podcast.py")
    PAGE.write_text(updated, encoding="utf-8")
    print("podcast.html updated — {} episodes".format(len(entries)))


if __name__ == "__main__":
    main()
